[package]
name = "velque"
version = "0.1.0"
edition = "2021"
description = "Velque: order book for tokenized stocks on Solana, day book, night auctions, opening cross"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
pinocchio = { version = "0.11.2", features = ["cpi"] }
pinocchio-token = "0.7.0"
pinocchio-system = "0.6.1"
pinocchio-associated-token-account = "0.4.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = "z"
strip = true
